# Generated by Django 5.0.4 on 2024-04-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_groups_employee_is_active_employee_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_staff',
        ),
    ]
